# nb-model_exp-results-3-2 (h_pba_h_h_vol_h)

In [1]:
import sys
import os
from os import sep
from os.path import dirname, realpath, exists, basename
from pathlib import Path
from glob import glob, iglob
import logging

def get_cwd(fname, subdir, crunch_dir=realpath(Path.home()) +sep +'crunch' +sep):
    """
    Convenience function to make a directory string for the current file based on inputs.
    Jupyter Notebook in Anaconda invokes the Python interpreter in Anaconda's subdirectory
    which is why changing sys.argv[0] is necessary. In the future a better way to do this
    should be preferred..
    """
    return crunch_dir +subdir +fname

def fix_path(cwd):
    """
    Convenience function to fix argv and python path so that jupyter notebook can run the same as
    any script in crunch.
    """
    sys.argv[0] = cwd
    module_path = os.path.abspath(os.path.join('..'))
    if module_path not in sys.path:
        sys.path.append(module_path)

fname = 'nb-model_exp-results-3-2.ipynb'
dir_name = 'model'
fix_path(get_cwd(fname, dir_name +sep))

import numpy as np
import pandas as pd

from ipywidgets import interact, interactive, fixed
from IPython.display import display

pd.set_option("display.max_rows", 300)
pd.set_option("display.max_columns", 50)

from common_util import MODEL_DIR, load_json, dump_json, rectify_json, load_df, str_now, makedir_if_not_exists, is_valid, isnt, compose, pd_split_ternary_to_binary, df_del_midx_level, midx_intersect, pd_get_midx_level, pd_rows, df_midx_restack
from common_util import NestedDefaultDict
from model.common import EXP_LOG_DIR, EXP_PARAMS_DIR, ASSETS, DATASET_DIR, XG_PROCESS_DIR, XG_DATA_DIR, XG_DIR, PYTORCH_MODELS_DIR, TRAIN_RATIO, EXPECTED_NUM_HOURS
from recon.viz import *
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)

CRITICAL:root:script location: /home/kev/crunch/model/nb-model_exp-results-3-2.ipynb
CRITICAL:root:using project dir: /home/kev/crunch/

Prune the xg data down to the data of interest to use in further experiments.

In [2]:
def get_bench(pattern):
    ndd = NestedDefaultDict()
    for path in iglob(pattern, recursive=True):
        ndd[path.split('/')] = load_json(path)

    df_idx = [k[2] for k in ndd.keys()]
    df = pd.DataFrame.from_records([b['benchmark-hold'] for b in ndd.values()], index=df_idx)

    return df

In [3]:
def consolidate_results(pattern, bench_pattern=None):
    ndd = NestedDefaultDict()
    for path in iglob(pattern, recursive=True):
        ndd[path.split('/')] = load_json(path)
    df_keys = [(k[2], k[3], k[4], k[5], k[6]) for k in ndd.keys()]
    df_idx = pd.MultiIndex.from_tuples(df_keys, names=('asset', 'model', 'data', 'params', 'trial')) \
        .remove_unused_levels()
    df = pd.DataFrame.from_records(list(ndd.values()), index=df_idx) \
        .reset_index() \
        .groupby(['asset', 'model', 'params']).mean() # average across trials for each study

    if (is_valid(bench_pattern)):
        bench_df = get_bench(bench_pattern)
        mets = ['accuracy', 'precision', 'recall', 'f1']
        rets = ['profit', 'sharpe', 'cagr']
        for m in mets+rets:
            res_cols = [c for c in df.columns if (c.endswith(m))]
            bench_cols = [c for c in bench_df.columns if (c.endswith(m))]
            bench_col = bench_cols[0]

            for asset in bench_df.index:
#                 print(bench_df.loc[asset, bench_col])
#                 print(df.xs(asset, level=0, drop_level=False)[res_cols])
                df.xs(asset, level=0, drop_level=False).loc[:, res_cols] -= bench_df.loc[asset, bench_col]
#     df = df.style \
#         .background_gradient(subset=[c for c in df.columns if c.endswith(('accuracy', 'profit', 'sharpe', 'cagr'))], cmap='BuGn')
#     .set_sticky(axis="index") \
    return df

In [4]:
def agg_asset(res_df):
    agg_df = res_df.groupby(['model', 'params']).mean()
    return agg_df

In [5]:
def agg_model(res_df):
    agg_df = res_df.groupby(['params']).mean()
    return agg_df

In [6]:
def agg_asset_params(res_df):
    return res_df.groupby(['asset', 'params']).mean()

In [7]:
def add_style(df):
    df = df.style \
         .background_gradient(subset=[c for c in df.columns if c.endswith(('accuracy', 'f1', 'profit', 'sharpe', 'cagr'))], cmap='BuGn')
#     .set_sticky(axis="index") \
    return df

In [8]:
view = ('accuracy', 'f1', 'profit', 'sharpe', 'cagr')

def select_ends(df, ends=view):
    res_cols = [c for c in df.columns if (c.endswith(ends))]
#     for m in ends:
#         res_cols = [c for c in df.columns if (c.endswith(m))]
    return df.loc[:, res_cols]

In [9]:
def select_paramrange(df, r):
    params = map(str, r)
    return df.loc[(slice(None), slice(None), params), :]

In [10]:
def dropfirstmi(df):
    df.index = df.index.droplevel(0)
    return df

def gb_filter_monotonic(df, checkcol='val_binary_sharpe'):
    return dropfirstmi(df.reorder_levels(['asset', 'params', 'model']) \
            .groupby('params') \
            .apply(lambda g: g if (g[checkcol].is_monotonic_increasing) else None) \
            .sort_index())

subgt = lambda g, big, small='base': (g.xs(big, level=2) > g.xs(small, level=2)).all()
monotonic_partial = lambda g: (subgt(g, 'lnp') and subgt(g, 'np', 'lnp')) or (subgt(g, 'cnp') and subgt(g, 'np', 'cnp'))

def gb_filter_monotonic_partial(df, checkcol='val_binary_sharpe'):
    return dropfirstmi(df.reorder_levels(['asset', 'params', 'model']) \
            .groupby('params') \
            .apply(lambda g: g if (monotonic_partial(g[checkcol])) else None) \
            .sort_index())

nonneg = lambda g: (g.xs('np', level=2) > 0).all() and (g.xs('lnp', level=2) > 0).all()

def gb_filter_neg(df, checkcol='val_binary_sharpe'):
    return dropfirstmi(df.reorder_levels(['asset', 'params', 'model']) \
            .groupby('params') \
            .apply(lambda g: g if (nonneg(g[checkcol])) else None) \
            .sort_index())

def gb_filter_lf(df, checkcol='val_binary_longfreq'):
    return dropfirstmi(df.groupby('params') \
            .apply(lambda g: g if ((g[checkcol].between(.2, .8)).all()) else None))

In [11]:
def range_diff(df, target_range, base_range):
    tgt = df.loc[map(str, target_range)]
    return tgt - df.loc[map(str, base_range)].set_index(tgt.index)

In [12]:
# def get_params_per_dataset():
#     EXP_LOG_DIR

In [13]:
exp_base = basename(dirname(EXP_LOG_DIR))
sm_name = 'anp'

drange = '2009_2018'
xdata = 'h_pba_h_h_vol_h'
ydata = 'ddir'
data_name = f'{drange}_{ydata}_{xdata}'
bench_data_name = f'{drange}_{ydata}'

path_train = f"{exp_base}/{sm_name}/**/{data_name}/**/train.json"
path_val =   f"{exp_base}/{sm_name}/**/{data_name}/**/val.json"
# path_test = f"{exp_base}/{sm_name}/**/{data_name}/**/test.json"

path_bench_train = f"{exp_base}/bench/*/{bench_data_name}/train.json"
path_bench_val = f"{exp_base}/bench/*/{bench_data_name}/val.json"
# path_bench_test = f"{exp_base}/bench/*/{bench_data_name}/test.json"

In [14]:
STUDY_START = 300
STUDY_END = 490
PRANGE = range(STUDY_START, STUDY_END)

# absolute results
dt = select_paramrange(consolidate_results(path_train), PRANGE);
dv = select_paramrange(consolidate_results(path_val), PRANGE);

# benchmark adjusted results
dt_adj = select_paramrange(consolidate_results(path_train, path_bench_train), PRANGE);
dv_adj = select_paramrange(consolidate_results(path_val, path_bench_val), PRANGE);

/home/kev/miniconda3/lib/python3.8/site-packages/pandas/core/indexing.py:1787: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, val, pi)

## Results
Parameter sets >= 300

In [15]:
train_clf = [col for col in dt.columns if ('clf' in col)]
train_binary = [col for col in dt.columns if ('binary' in col)]
train_binary_sharpe = [col for col in train_binary if (col.endswith('sharpe'))]

In [16]:
val_clf = [col for col in dv.columns if ('clf' in col)]
val_binary = [col for col in dv.columns if ('binary' in col)]
val_binary_sharpe = [col for col in val_binary if (col.endswith('sharpe'))]

In [17]:
add_style(agg_model(agg_asset(dt_adj.loc[:, train_binary_sharpe])))

In [18]:
add_style(agg_model(dv_adj.loc[:, val_binary_sharpe]))

In [19]:
base_range = range(STUDY_START, STUDY_START+10)

### Compare study interventions globally

In [20]:
pavg = agg_asset_params(dv_adj.loc[:, val_binary_sharpe]).sort_index(level=[1, 0]).groupby('params').mean()

In [21]:
res = []
for start in range(STUDY_START+10, STUDY_END, 10):
    r = range(start, start+10)
    ser = range_diff(pavg, r, base_range).mean()
    ser.name = start
    res.append(ser)
res = pd.concat(res, axis=1).transpose()
add_style(res)

In [22]:
# Information Ratio:
res = []
for start in range(STUDY_START+10, STUDY_END, 10):
    r = range(start, start+10)
    ser = range_diff(pavg, r, base_range).mean() / range_diff(pavg, r, base_range).std()
    ser.name = start
    res.append(ser)
res = pd.concat(res, axis=1).transpose()
add_style(res)

### Compare study interventions for each asset

In [23]:
asset_pavg = dv_adj.loc[:, val_binary_sharpe].groupby(['params', 'asset']).mean()

In [25]:
res = []
for start in range(STUDY_START+10, STUDY_END, 10):
    r = range(start, start+10)
    ad = range_diff(asset_pavg, r, base_range).groupby('asset').mean()
    ad = ad.assign(start=start).set_index('start', append=True)
    res.append(ad)
res = pd.concat(res, axis=0).sort_index(level=[0, 1])
add_style(res)

In [26]:
res = []
for start in range(STUDY_START+10, STUDY_END, 10):
    r = range(start, start+10)
    #ad = range_diff(asset_pavg, r, base_range).groupby('asset').mean()
    ad = range_diff(asset_pavg, r, base_range).groupby('asset').mean() / range_diff(asset_pavg, r, base_range).groupby('asset').std()
    ad = ad.assign(start=start).set_index('start', append=True)
    res.append(ad)
res = pd.concat(res, axis=0).sort_index(level=[0, 1])
add_style(res)

In [36]:
#add_style(agg_asset_params(dv_adj.loc[:, val_binary_sharpe]).sort_index(level=[1, 0]))

## Recover Best Params By Asset

In [82]:
res = []
for start in range(STUDY_START+10, STUDY_END, 10):
    r = range(start, start+10)
    ad = range_diff(asset_pavg, r, base_range).groupby('asset').mean()
    ad = ad.assign(start=start).set_index('start', append=True)
    res.append(ad)
res = pd.concat(res, axis=0).sort_index(level=[0, 1])
topgroups = res.loc[res.groupby(['asset'])['val_binary_sharpe'].idxmax()]
add_style(topgroups)

In [83]:
res = []
for start in range(STUDY_START+10, STUDY_END, 10):
    r = range(start, start+10)
    #ad = range_diff(asset_pavg, r, base_range).groupby('asset').mean()
    ad = range_diff(asset_pavg, r, base_range).groupby('asset').mean() / range_diff(asset_pavg, r, base_range).groupby('asset').std()
    ad = ad.assign(start=start).set_index('start', append=True)
    res.append(ad)
res = pd.concat(res, axis=0).sort_index(level=[0, 1])
topgroups = res.loc[res.groupby(['asset'])['val_binary_sharpe'].idxmax()]
add_style(topgroups)

In [84]:
bestparams = {}
for group in topgroups.index:
    asset, start = group
    bestgroup = dv_adj.xs((asset, 'np')).loc[str(start):str(start+9), val_binary_sharpe]
    bestidx = bestgroup.loc[:, ['val_binary_long_sharpe', 'val_binary_short_sharpe']].mean(axis=1).idxmax()
    bestparams[asset] = int(bestidx)
    display(asset, add_style(bestgroup))

'dow_jones'

'nasdaq_100'

'russell_2000'

'sp_500'

In [86]:
bestparams

{'dow_jones': 447, 'nasdaq_100': 425, 'russell_2000': 338, 'sp_500': 376}

## Compare Results Over Val by Params

In [42]:
sel_param = lambda d, p: d.xs(p, level=2, drop_level=False)
sel_asset = lambda d, a: d.xs(a, level=0, drop_level=False)

In [43]:
sp_500 = sel_asset(dv_adj.loc[:, val_binary_sharpe], 'sp_500').sort_index(level=2)
russell_2000 = sel_asset(dv_adj.loc[:, val_binary_sharpe], 'russell_2000').sort_index(level=2)
nasdaq_100 = sel_asset(dv_adj.loc[:, val_binary_sharpe], 'nasdaq_100').sort_index(level=2)
dow_jones = sel_asset(dv_adj.loc[:, val_binary_sharpe], 'dow_jones').sort_index(level=2)

In [44]:
add_style(sp_500)

In [45]:
add_style(gb_filter_monotonic(sp_500))

In [46]:
add_style(gb_filter_neg(gb_filter_monotonic_partial(sp_500)))

In [47]:
add_style(gb_filter_monotonic(russell_2000))

In [48]:
add_style(gb_filter_neg(gb_filter_monotonic_partial(russell_2000)))

In [ ]:
add_style(gb_filter_monotonic(nasdaq_100))

In [ ]:
add_style(gb_filter_neg(gb_filter_monotonic_partial(nasdaq_100)))

In [ ]:
add_style(gb_filter_monotonic(dow_jones))

In [ ]:
add_style(gb_filter_neg(gb_filter_monotonic_partial(dow_jones)))